/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AegirSDR.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9ddcbfb9e55cc8890e2eb2d4a79e9bac)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/Aegir/AegirSDR.h>
// pydoc.h is automatically generated in the build directory
#include <AegirSDR_pydoc.h>

void bind_AegirSDR(py::module& m)
{

    using AegirSDR    = gr::Aegir::AegirSDR;


    py::class_<AegirSDR, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<AegirSDR>>(m, "AegirSDR", D(AegirSDR))

        .def(py::init(&AegirSDR::make),
             py::arg("address"),
             py::arg("ctrl_address"),
             py::arg("nchannels"),
             py::arg("blocksize"),
             py::arg("frequency"),
             py::arg("samplerate"),
             py::arg("gain"),
             py::arg("timeout_ms") = 100,
             D(AegirSDR,make)
        )
        .def("set_frequency",  &AegirSDR::set_frequency,  py::arg("freq"))
        .def("set_samplerate", &AegirSDR::set_samplerate, py::arg("samplerate"))
        .def("set_gain",       &AegirSDR::set_gain,       py::arg("gain"))
        



        ;




}








