%AegirSDR
%
%Matlab script demonstrating CZMQSDR2

%Receive samples, examine spectrum (in realtime if possible, but zmq-
%buffers can and will stretch if matlab polls the socket too slowly).

clear all;close all;

sdr = CZMQSDR('IPAddress','127.0.0.1');
FESR = 2e6;
nSample = 2^16;
scope = dsp.SpectrumAnalyzer(...
    'Name',             'Spectrum',...
    'Title',            'Spectrum', ...
    'SpectrumType',     'Power',...
    'FrequencySpan',    'Full', ...
    'SampleRate',        FESR, ...
    'YLimits',          [-50,5],...
    'SpectralAverages', 100, ...
    'FrequencySpan',    'Start and stop frequencies', ...
    'StartFrequency',   -FESR/2, ...
    'StopFrequency',    FESR/2);

sdr();
%sdr.CenterFrequency = 95e6; %91.9e6;% -40e3;
while 1
    x = sdr();
    x = x - mean(x);
    scope(x);
end

release(sdr);